<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
    <Company>EveHQ Development Team</Company>
    <AssemblyVersion>2.15.0</AssemblyVersion>
    <FileVersion>2.15.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveHQ.Caching\EveHQ.Caching.csproj" />
    <ProjectReference Include="..\EveHQ.Common\EveHQ.Common.csproj" />
    <ProjectReference Include="..\EveHQ.EveData\EveHQ.EveData.csproj" />
  </ItemGroup>

</Project>
