<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputPath>..\BuildOutput\EveHQ\$(Configuration)\</OutputPath>
    <RootNamespace>EveHQ.HQF</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

 <ItemGroup>
    <Reference Include="DevComponents.DotNetBar2">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Ref\DotNetBar\DevComponents.DotNetBar2.dll</HintPath>
    </Reference>
    <PackageReference Include="protobuf-net" Version="3.2.52" />
  </ItemGroup>

  <ItemGroup>
   <Reference Include="Microsoft.VisualBasic" />
   <PackageReference Include="System.Resources.Extensions" Version="9.0.6" />
   <Reference Include="System.Windows.Forms.DataVisualization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveHQ.Core\EveHQ.Core.vbproj" />
  </ItemGroup>

</Project>
