<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EveHQ.Core</RootNamespace>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DevComponents.DotNetBar2">
      <HintPath>..\Ref\DotNetBar\DevComponents.DotNetBar2.dll</HintPath>
    </Reference>
    <Reference Include="GammaJul.LgLcd">
      <HintPath>..\Ref\G15 Drivers\GammaJul.LgLcd.dll</HintPath>
    </Reference>
    <Reference Include="System.Design" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Security" />
    <Reference Include="System.Web" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq">
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveHQ.CoreLib\EveHQ.CoreLib.csproj" />
    <ProjectReference Include="..\EveHQ.Esi\EveHQ.Esi.csproj" />
    <ProjectReference Include="..\EveHQ.EveData\EveHQ.EveData.csproj" />
    <ProjectReference Include="..\EveHQ.Market\EveHQ.Market.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ionic.Zip" Version="1.9.1.8" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
    <PackageReference Include="System.Resources.Extensions" Version="9.0.6" />
    <PackageReference Include="System.Xml.Linq" Version="3.5.21022.801" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\refresh.png" />
    <None Include="Resources\EveHQ_IGBLogo1.jpg" />
    <None Include="Resources\EveHQ_LCDLogo.png" />
    <None Include="Resources\ArrowDown.png" />
    <None Include="Resources\ArrowUp.png" />
    <None Include="Resources\Info32.png" />
    <Content Include="Resources\nochar.jpg" />
    <None Include="Resources\IGBAccess.csv" />
    <None Include="Resources\Orders321.png" />
    <None Include="Resources\SkillBookClosed32.png" />
    <None Include="Resources\level5_act.gif" />
    <None Include="Resources\level4_act.gif" />
    <None Include="Resources\level3_act.gif" />
    <None Include="Resources\level2_act.gif" />
    <None Include="Resources\level1_act.gif" />
    <None Include="Resources\SkillBook32.png" />
    <None Include="Resources\SQLQueries.txt" />
    <None Include="Resources\Strings.txt" />
    <None Include="Resources\EveHQ_IGBLogo.jpg" />
  </ItemGroup>

</Project>
