<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputPath>..\BuildOutput\CacheCreator\$(Configuration)\</OutputPath>
    <RootNamespace>EveHQ.Prism</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveHQ.Core\EveHQ.Core.vbproj" />
    <ProjectReference Include="..\EveHQ.EveData\EveHQ.EveData.csproj" />
  </ItemGroup>

  <ItemGroup>
   <Reference Include="DevComponents.DotNetBar2">
     <SpecificVersion>False</SpecificVersion>
     <HintPath>..\Ref\DotNetBar\DevComponents.DotNetBar2.dll</HintPath>
   </Reference>
   <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
   <Reference Include="System.Web" />
   <PackageReference Include="System.Resources.Extensions" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\icon33_02.png" />
  </ItemGroup>

</Project>
