<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <OutputPath>..\BuildOutput\CacheCreator\$(Configuration)\</OutputPath>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>EveHQ.CacheCreator</RootNamespace>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveHQ.EveData\EveHQ.EveData.csproj" />
    <ProjectReference Include="..\EveHQ.HQF\EveHQ.HQF.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

</Project>