namespace EveHQ.CoreLib;

/// <summary>
/// A list of available API types that can be obtained from API Servers
/// </summary>
public enum APITypes : int
{
    SkillTree = 0,
    RefTypes = 1,
    AllianceList = 2,
    Sovereignty = 3,
    Characters = 4,
    CharacterSheet = 5,
    SkillTraining = 6,
    WalletJournalChar = 7,
    WalletJournalCorp = 8,
    WalletTransChar = 9,
    WalletTransCorp = 10,
    AccountBalancesChar = 11,
    AccountBalancesCorp = 12,
    CorpMemberTracking = 13,
    AssetsChar = 14,
    AssetsCorp = 15,
    KillLogChar = 16,
    KillLogCorp = 17,
    Conquerables = 18,
    CorpSheet = 19,
    ErrorList = 20,
    IndustryChar = 21,
    IndustryCorp = 22,
    OrdersChar = 23,
    OrdersCorp = 24,
    MapJumps = 25,
    MapKills = 26,
    NameToID = 27,
    IDToName = 28,
    POSList = 29,
    POSDetails = 30,
    StandingsChar = 31,
    StandingsCorp = 32,
    // StandingsAlliance = 33,
    CorpContainerLog = 34,
    CorpTitles = 35,
    CorpMemberSecurity = 36,
    CorpMemberSecurityLog = 37,
    CorpShareholders = 38,
    FWStatsChar = 39,
    FWStatsCorp = 40,
    FWTop100 = 41,
    FWMap = 42,
    ServerStatus = 43,
    CertificateTree = 44,
    MedalsReceived = 45,
    MedalsAvailable = 46,
    MemberMedals = 47,
    SkillQueue = 48,
    SovereigntyStatus = 49,
    MailMessages = 50,
    Notifications = 51,
    MailingLists = 52,
    MailBodies = 53,
    Research = 54,
    AccountStatus = 55,
    CalendarEventAttendeesChar = 56,
    // CalendarEventAttendeesCorp = 57,
    UpcomingCalendarEvents = 58,
    CharacterInfo = 59,
    OutpostList = 60,
    OutpostServiceDetail = 61,
    ContactListChar = 62,
    ContactListCorp = 63,
    APIKeyInfo = 64,
    ContractsChar = 65,
    ContractsCorp = 66,
    ContractItemsChar = 67,
    ContractItemsCorp = 68,
    ContractBidsChar = 69,
    ContractBidsCorp = 70,
    NotificationTexts = 71,
    ContactNotifications = 72,
    FWStats = 73,
    CallList = 74,
    BlueprintsChar = 75,
    BlueprintsCorp = 76,    
}