<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveHQ.Caching\EveHQ.Caching.csproj" />
    <ProjectReference Include="..\EveHQ.Common\EveHQ.Common.csproj" />
    <ProjectReference Include="..\EveHQ.NewEveAPI\EveHQ.NewEveAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

</Project>
