<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputPath>..\BuildOutput\CacheCreator\$(Configuration)\</OutputPath>
    <RootNamespace>EveHQ.KillMailViewer</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveHQ.Common\EveHQ.Common.csproj" />
    <ProjectReference Include="..\EveHQ.Core\EveHQ.Core.vbproj" />
    <ProjectReference Include="..\EveHQ.EveData\EveHQ.EveData.csproj" />
    <Reference Include="DevComponents.DotNetBar2">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Ref\DotNetBar\DevComponents.DotNetBar2.dll</HintPath>
    </Reference>
    <PackageReference Include="System.Resources.Extensions" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\icon26_05.png" />
  </ItemGroup>

</Project>
